name: build-project

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint-chart:
    name: Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint chart
        run: helm lint .

      - name: Template render test
        run: helm template test-render . --debug

  mandatory-checks:
    name: End of PR checks
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - run: exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
    needs:
      - lint-chart
